image:
  pullPolicy: IfNotPresent
imagePullSecrets: []

resources:
  # Interesting Config:
  # resource name exposed by Orion
  name: "virtaitech.com/gpu"

monitor:
  collectorPath: /run/prometheus
  image:
    exporter:
      repository: virtaitech/dcgm-export #nvidia/dcgm-exporter
      version: "2.2"
    prometheus:
      repository: virtaitech/node-exporter #quay.io/prometheus/node-exporter
      version: "2.2"
  # this port is also used by controller to scrap info.
  # should not change this value
  port: 9100

controller:
  version: "2.2"
  name: "orion-controller"
  port: "15500"
  portName0: "controller"
  portName1: "port1"
  portName2: "webportal"
  nodeport: 30007
  service: orion-controller
  image:
    prom: virtaitech/prometheus
    repository: virtaitech/orion-controller
    version: "2.2"
  # Interesting Config:
  password: "admin"
  # Interesting Config:
  enableQuota: false # or true
  # Interesting Config:
  token: ""
  # changing this value not tested
  replicas: 1

helper:
  image:
    repository: virtaitech/orion-helper
    version: "2.2"

server:
  port: "9960"
  #mode: "rdma"
  # Interesting Config:
  # TODO: requires addtional images
  cudaVersion: "10.1"
  image:
    version: "2.2"
  path:
    comm: /var/tmp/orion/comm
  # Interesting Config:
  net: ens5
  # Interesting Config:
  vgpus: 4
  # Interesting Config:
  ibName: ""

plugin:
  path: /var/lib/kubelet/device-plugins
  image:
    repository: virtaitech/orion-plugin
    version: "2.2"

scheduler:
  replicas: 1
  apiVersion: "2.2"
  dataVersion: "2.2"
  image:
    scheduler:
      repository: virtaitech/hyperkube #gcr.io/google_containers/hyperkube:v1.16.3
      version: "2.2"
    extender:
      repository: virtaitech/k8s-scheduler-extender
      version: "2.2"
  port: 8888
  verbose: 4

license:
  # Interesting Config:
  key: "S1ZMb1o2T2F2cC80MGpXalVUaFBUUEhuPWg9eDNmcW41UHlGd0ZPUHhPZXNzcnNqWENMcU5qT09Dc244bFRUNFpuUHJNcSs0UStoeW1SbEpXV2NXWjJzUkZyNlpiR2FzcjZ1c09aRXc9YUphSnJ4UmJyLzVRbXEyND1Lb0FrV3EvbGNUVHpHdEMxTm5OR0xMdk5rQTQ0azl5SWtXNGZjQ0dBc2pMbjU2UkhGZjh6TkJtZlpvZjFPajhzM3RtZmF3dGtzWjhiOGd5QlBCVU8yclE9SFBkMU00ZVZ3MEVaK2FHeFk0VWNKazVYYlRZZU5vemJnVktmajVXWk5Zb1QvU1ltVEU3ZFRSWjMvRDN2K2NvdXRob2lnc3JZYzljOXVMTmhTQTlKVUhXVUlySHNkc3REOC9LY2xWWEhlVUNJNVZJLzRnMU1sQXI9UGd6PWp4bThJbm85bXhrdjFKVHZPcS9nNGtZTkxCczNXZjZQYTYyd3M9ZFZzaUJVSHNGL2JKcVZHNVhNT3F3bUQ0NmlQVEJKSWxYeUVTWG15NVJvRU9EL09OcTRaYTJuRXdjSmNtSFF0d3p1QXlvUlNoczd6YXBTaVQvaE9sTSt5dGU5VmdKRjVibzZUMkEzMUE0RUVobjcvSnFLL01iR25SWVV0enlUWmZ2eW9BZDN2QlhJRlNGVHArMmtaWFZVMTRMZ2FRNnduTGVFZEVRL1YrTGNlaFBqSWJ0akhMZUlKbzZwL1lGUnE2PUR3Q1pKOFRRbVpDbFZja0E1V1lEZnlSTzU9WEVMUnFLS3VkRzFQQTEyMVRoWmx1aTM5SE1tcE9VQ0Z3L2pXS1p1MElJc25PbmszNUpxMk9EVEFQWkdhMk0waTArMytpYkFuZ0xMaFExNjI0TUlJRXZRSUJBREFMQmdrcWhraUc5dzBCQVFFRWdnU3BNSUlFcFFJQkFBS0NBUUVBeUpZSTNNUldCZ2cvYTB4WXZEN0tEU3JOcm5uclVubzNVQkk2TmV3enQ3WGExY0RLRWNrVWhROVhJUUQxRU9HVWswMituM1V4eXNCYk96c3p5UXlRMjM0ZWFSWEdsUFUwZnpzVXNwK0daZmJJdjY2d3BjOEdwVWNFamhaaE84ZURjaUprSzQxcnMrSnE4bDBXZkk0cDh6dy9tOURiVWx4RHlHWnAxNGZjYkk1WlM2UDF5WUhOdnVjdFZtemM4c1RTTEpaZVZPUEZWZlA5a0R3ZUZXK3lYRWM2Z1N2MUFsc29JdFA2V0taU3czeTRJdWJTczhlc0NXZ0pSQ0lJc2JLWGh4QWZZY2poSEFjWGwxTkxoelMyWXNwa2YycTZhZ1RxWEZUR0ttOGU1UkdSZWMreEtjUjdvZXBJbmw4blhocnlrWW4rSnU3THNHUmQ5L0Z6WHVFNUdRSURBUUFCQW9JQkFDUDNPdm1TdnJYd0xxYm5scFdTVUpwUnpYVjJhT3B0L1pMKzRhOGZmaHAzb2hobnJCUEtVVUtXZ0pIcllRVzQzUElZbzVCbDdCcWxxUFlTNUhNdExLQWVtZ2RQbno3QVJMeDNkSHVldlBOMWI0Tm5LRWRpdXBkU0I1QU9sVHFweUhqamo4QjdhQTltRHJVTVdlYlZldEloUUdxSTVYcDhEcTlWSmE4K3JoaE1rRnZ3dkRYZ1diUzFiZjRCOFQ1YkFsU1lpSGJyYTk5WVZZVCswMi9WUHBzZjRBQWpMWEZkbXM3QmVHR0hETXJGNDZCNU8zNmVuMm1PTmcyQlQ0alIxK0svajk4Zi9NWFlFZStScFNZcUh4R3o4NHloYXdUS1BsL0RLTElXYTRaL3NBNjlpeHpQamQyMzRDYkNIZ256c1hyRkZmUVVSdjRIYmVsRjdEdUVObjBDZ1lFQTBuTllvZzMwTm0yUGJGQUxxY0graEZuMjNXRVV5aDhIOXc5SjZOOTI4aDFQSmZ4YmpuWGR0dFZ1dkZzeXdzZDZscDJreHhpOWZzS3RyeHdyY0JZOG9QZzR0NXFzRTJ2Tlc5RWgvWlUzakl1UDcvbkVvbTNLM0xFN0hndmhVeWxGVVl1MWVHTXYwcWRCU0ZJdGd2cTNVQ1FPN3hpM1RrZ2NDb2N4Y3BCOGpyc0NnWUVBOUFBZHFXRWhyT2ZnZHJvdEJMelR5OFhMWU04ZjJta3RKUlZNQ3BXU3A3VWs3dnQ1bzNoOWNGWCtvVW13M0FxQXB0YlRWUzJXWXducFR1WTFBcWZaTTdKWGd2NmFXdGJyZHFLZ1RwL3dkUnp3N0l2OU13UXh5d3hzK2M4a3h1WWszRXZVOG8yLytmaWp4b2ZoUjhGYStlM3YwQXh5ZGhwQ2lFYkY4SVhodkRzQ2dZRUF5Nlk1SCtDMjhUQ0dPTDhnK2k0ekdHcGlmSW5rYjA4bUN3c3RiMzlIZ0RXaWtOU3EyS253V213aFUzNUJHY0dsUERqaTZwTmpWRllaY3Jta3d6dVJnZ2VTQXdKWEFCZ3l5bVlQS1hBTEtDTXByNFNZcHNIdUxEQUpVQ01ZOGJ1ZlM3RVJjNlV2OHY1Tkt5bnl4cXZOVm16K1Vwc3RUMEJ5ZWpHblJRRFN0OThDZ1lFQXhyOEphaHdxRi9MUHpTV2M0YzBGSDJnL1h0Mlhib3BaTVdtRmhPR01rWHBsV1J3Uldtd2NrTkliRkRrNERDT3A0enY4NjlhME5udXVSSXdUQmRTK2dQTjFnTWZ0NXF4RkkxOFlBTE1hWStwcysrQ1RIMmo5UGcwaS91QVJic21yb0oxTUdUNEk3NDN0cVJxcEQ0K1prUmFVVGZ5MWh5bWdvK3d4OHRhNnBsMENnWUVBZy9XNFZZQXgvb0EycE1RdmpRZi8yZGluMjVORjNSdXcwZ01QZTlaL3VmOTVEMWZTOG1DSWh4K1ZPajc5UmREbVY1SHZXUFVQNnVhZVhNYWt0QWo0cG5NekZ1dTRSS3hZcVluWjMrWXhmVVZ5VjN0ZXFxSEpldE1nbUMwbi9xaUl5bnhDc2J2SjAreEVqYkF6ZGZzQVpUL3FPNStmUXF3RCtMN1Nielp3Skt3PTAyNTZOT2NCOGYxa0RWcmtTNU1LTTRZcHpHWENESkpzdVkvSDRjMXZnMjg4bDZTeEFZVHFBUk1Bcm9NMTVyK0hra21aRjBuVnRObExEV21rUWRmQjdDZDBXeXc0QUNHeGtscWdYMGwxMlM1eHNvdTU4ST1zMHo5UlhyOXUwRHVYZE5hYS9MRXUxbmtpUGFMQjVzRENOQ3RVZ20wTTI2Yk12Q3lhYTRwSGlxS2E9SE5xbTFxVFp0Q29Gc0ZQcUtYRkxlNU1BUE5XL2xkTnVycWg4R3RIVjE0ZGNEOUFFcGtwdFBpdE5jZGdFUkpWaEcyTXFmTFY2dERqeUhyQ1RPQ21rNm9FekdLUTI0PTFVbjFIZHFSSVBXK3F5RHNmZ1NoQklJRHU2bmswd3JRS2NkPTNpZjY2azQ5VFVBMmJTRGRoZj1nb3FDbzRpMGh4QUpKd1ROZGg5aElRcjIxPS84RC95YzlZUUJmSDF5YU5WcEV5S1FLdVAxY1RFaWRyU1NPSkxRUnBucEFudzg9PUJEUjlWQzdnL1ZUYVpVcUJjdjVidVRUdTZoSkpSZ1ZkajFHY2lKaGpYdnRQbzh2NnluPVNnSnBjcXIvOD1WcXVaZnVJbno9R1VCdElobVdoaHpYOWpRRjRNMThKbkxFcUsvMnJYNDViS04wS1pYTkpsRjhQamxacDlWWFE0QVNTdUVDNXNJTDV6d3RicEppS0Jlcnh2VVFIeUVGZ2RLMEQ9ZW5XTlhrbFhBS2o5aDRENTVNSWt2V2dmYVpJL0tjc1ZmZzNRaFpTYnlybVZqOGpaTlBrODB0UVcvTEVWaS9zVnFmajQ9T0lQRFFGYUwwRmx0SVowMDAwMDI1Np4121YPZ0rF7ibmAszLzdoGcRrCxtdoAlTxssbFCJXyxOwu5xyK5mN9LeY02uXIjCOPpCbpL9537fTx3Z4D6yiDCBiUMJUudKQ1CjqBVHPdHkFaQVzZqP1W39wUXiil3OjMK/L96p/dJdE23sISSla5tekX4VPEHHS5mzSAdpNcpUIK0/jGw9LQMVMhtTbpiePMpOFRPQPDMD3jJ5IR5sfZlJf1ckGoiEfgTcSRpLK3hopdEf2OnefYqD2uipqb3VCppEr6a58Z6fsiBr0ERXr9xWCbRZstO7woQLv7/ID1FYOzc2YCCLr2HTHFn/IJUAmPhEHQs/iExGvFCvvbOcQ="

volumes:
  shm: /dev/shm
