image:
  pullPolicy: IfNotPresent
imagePullSecrets: []

resources:
  name: "virtaitech.com/gpu"

monitor:
  collectorPath: /run/prometheus
  image:
    exporter:
      repository: virtaitech/dcgm-export #nvidia/dcgm-exporter
      version: "2.1"
    prometheus:
      repository: virtaitech/node-exporter #quay.io/prometheus/node-exporter
      version: "2.1"
  port: 9100

controller:
  port: "15500"
  nodeport: 30007
  service: orioncontroller
  image:
    prom: virtaitech/prometheus
    repository: virtaitech/orion-controller-ent
    version: "2.1"
  password: "admin"
  enableQuota: false # or true
  token: ""
  replicas: 1

server:
  port: "9970"
  mode: "rdma"
  cudaVersion: "10.1"
  image:
    version: "2.1"
  path:
    comm: /var/tmp/orion/comm
  net: enp3s0
  vgpus: 4
  ibName: ""

plugin:
  path: /var/lib/kubelet/device-plugins
  image:
    repository: virtaitech/orion-plugin
    version: "2.1"

scheduler:
  replicas: 1
  apiVersion: "2.1"
  dataVersion: "2.1"
  image:
    scheduler:
      repository: virtaitech/hyperkube #gcr.io/google_containers/hyperkube:v1.16.3
      version: "2.1"
    extender:
      repository: virtaitech/orion-scheduler-extender
      version: "2.1"
  port: 8888
  verbose: 4

license:
  key: ""

volumes:
  shm: /dev/shm