image:
  pullPolicy: IfNotPresent
imagePullSecrets: []

resources:
  name: "virtaitech.com/gpu"

monitor:
  collectorPath: /run/prometheus
  image:
    exporter:
      repository: nvidia/dcgm-exporter
    prometheus:
      repository: quay.io/prometheus/node-exporter
  port: 9100

controller:
  port: "15500"
  service: orioncontroller
  image:
    repository: virtaitech/orion-controller
    version: "2.1"
  password: "admin"
  enableQuota: "false" # or "true"
  token: "TODO"
  replicas: 3

server:
  port: "9970"
  mode: "rdma"
  image:
    repository: virtaitech/orion-cu10.0-tf1.13-py36-hvd
    version: "2.1"
  path:
    comm: /var/tmp/orion/comm
  net: enp3s0
  vgpus: "4"
  ibName: ""

plugin:
  image:
    repository: virtaitech/orion-plugin
    version: "2.1"

scheduler:
  apiVersion: "2.1"
  dataVersion: "2.1"
  image:
    scheduler:
      repository: gcr.io/google_containers/hyperkube
      version: v1.16.3
    extender:
      repository: virtaitech/orion-scheduler-extender
      version: "2.1"
  port: 8888

license:
  key: ""

volumes:
  shm: /dev/shm