apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    name: controller
spec:
  selector:
    matchLabels:
      app: orion
      name: controller
  replicas: 1
  template:
    metadata:
      labels:
        app: orion
        name: controller
    spec:
      containers:
      - name: controller
        image: '{{ .Values.controller.image.repository }}:{{ default .Chart.AppVersion .Values.controller.image.version }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.imagePullSecrets }}
        imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
        {{- end }}
        env:
        - name : PORT
          value : {{ .Values.controller.port }}
        ports:
        - name: controller
          containerPort: {{ .Values.controller.port | atoi }}
        env:
        - name: ORION_LICENSE
          value: {{ .Values.license.key }}

