apiVersion: v1
kind: Service
metadata:
  name: orion-controller-nodeport
spec:
  type: NodePort
  selector:
    app: orion
    name: {{ .Values.controller.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.controller.port | atoi }}
    targetPort: controller
    nodePort: {{ .Values.controller.nodeport }}
    name: {{ .Values.controller.portName0 }}
  - protocol: TCP
    port: {{ .Values.controller.port | atoi | add 1 }}
    targetPort: port1
    nodePort: {{ .Values.controller.nodeport | add 1 }}
    name: {{ .Values.controller.portName1 }}
  - protocol: TCP
    port: {{ .Values.controller.port | atoi | add 2 }}
    targetPort: port2
    nodePort: {{ .Values.controller.nodeport | add 2 }}
    name: {{ .Values.controller.portName2 }}