apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: orion-plugin
  labels:
    k8s-app: virtaitech
spec:
  selector:
    matchLabels:
      name: orion-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: orion-plugin
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - image: '{{ .Values.plugin.image.repository }}:{{ default .Chart.AppVersion .Values.plugin.image.version }}'
        {{- if .Values.imagePullSecrets }}
        imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
        {{- end }}
        name: orion-plugin
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: 
              - ALL
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: device-shm
            mountPath: {{ .Values.volumes.shm }}
        env:
        - name : ORION_CONTROLLER
          value : '{{ .Values.controller.service }}:{{ .Values.controller.port | atoi }}'
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: device-shm
          hostPath:
            path: {{ .Values.volumes.shm }}
