apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-scheduler
  namespace: kube-system
  labels:
    app: orion-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion-scheduler
  template:
    metadata:
      labels:
        app: orion-scheduler
    spec:
      serviceAccountName: orion-scheduler
      volumes:
      - name: orion-scheduler-config
        configMap:
          name: orion-scheduler-config
      containers:
      - name: orion-scheduler-ctr
        image: '{{ .Values.scheduler.image.scheduler.repository }}:{{ .Values.scheduler.image.scheduler.version }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - kube-scheduler
        - --config=/orion-scheduler/config.yaml
        - -v=4
        volumeMounts:
        - name: orion-scheduler-config
          mountPath: /orion-scheduler
      - name: orion-scheduler-extender-ctr
        image: '{{ .Values.scheduler.image.extender.repository }}:{{ default .Chart.AppVersion .Values.scheduler.image.scheduler.version }}'
        command: ["/go/bin/scheduler"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: ORION_CONTROLLER
            value: "controller.default.svc.cluster.local:5678"
          - name: ORION_API_VERSION
            value: {{ default .Chart.AppVersion .Values.scheduler.apiVersion }}
          - name: ORION_DATA_VERSION
            value: {{ default .Chart.AppVersion .Values.scheduler.dataVersion }}
          - name: MANAGED_ORION_SERVER
            value: "true" # always true for helm chart
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.scheduler.port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.scheduler.port }}
        ports:
          - containerPort: {{ .Values.scheduler.port }}