apiVersion: v1
kind: Pod
metadata:
 name: controller
 labels:
  name: controller
spec:
 nodeName: master
 restartPolicy: Never
 hostNetwork: true
 containers:
 - name: controller
   image: orion-controller:dtf
   imagePullPolicy: IfNotPresent
   env:
     - name : PORT
       value : "9125"

