apiVersion: v1
kind: Pod
metadata:
  generateName: orion-client-100-
spec:
  nodeName: master
  restartPolicy: Never
  hostNetwork: true
  containers:
  - name: orion-client-100
    image: orion-client:dtf
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /root/test
      name: test
    - mountPath: /usr/lib/orion/liborion.cuda-9.0.so
      name: lib-bin
    command: ["bash", "-c"]
    args: ["echo 'Sleeping for 10 hours ...'; sleep 10h"]
    resources:
      limits:
        virtaitech.com/gpu: 1
    env:
      - name : ORION_GMEM
        value : "4096"
      - name : ORION_RATIO
        value : "100"
  volumes:
  - name: test
    hostPath:
      path: /root/test
  - name: lib-bin
    hostPath:
      path: /root/liborion.so.9.0
      type: File


