apiVersion: v1
kind: Pod
metadata:
  name: orion-client-paddle
spec:
  nodeName: master
  restartPolicy: Never
  hostNetwork: true
  containers:
  - name: orion-client
    image: virtaitech/orion-client:cu10.0-paddle1.5-py3
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /root/test
      name: test
    - mountPath: /usr/lib/orion/liborion.cuda-10.0.so
      name: lib-bin
    command: ["bash", "-c"]
    args: ["echo 'Sleeping for 10 hours ...'; sleep 10h"]
    resources:
      limits:
        virtaitech.com/gpu: 1  
    env:
      - name : ORION_GMEM
        value : "7500"
      - name : ORION_RATIO
        value : "100"
  volumes:
  - name: test
    hostPath:
      path: /root/test
  - name: lib-bin
    hostPath:
      path: /root/liborion.so.10.0
      type: File



